### ISSUE TITLE
SELECT IMAGEの2回目以降が1枚目の画像のままとなる。(1回目と2回目の画像が異なる場合)

### ISSUE THREAD

**Issue by ryuone** [Lebe-Inc/react-handson-vol2#3]
react-handson-vol2/level2/src/javascripts/components/edit/canvas/CanvasView.jsx
```
  componentWillUnmount(){
    image = null;
  }
```
無理矢理ですが、上記で画像が読み込まれます。

**Comment by ryuone** [comment]
すみません。completeブランチで再度確認してみます〜。

**Comment by kamiyam** [comment]
これらしいですｗ

が、mountごとにセットしないさ無いとだめっぽいですね。

https://github.com/Lebe-Inc/react-handson-vol2/blob/complete/level2/src/javascripts/components/edit/canvas/CanvasView.jsx#L3

**Comment by ryuone** [comment]
以下の行が初回しか通らないですね。。。
(画像選択しなおしても、image変数は前回のImageインスタンスを持ってますね。どうするのがベストなのかな。)

https://github.com/Lebe-Inc/react-handson-vol2/blob/complete/level2/src/javascripts/components/edit/canvas/CanvasView.jsx#L59

**Comment by konojunya** [comment]
@ryuone completeブランチもimageの問題は解決できておらずそのままだと思います。。

React的には`CanvasView`コンポーネントがもっている状態なのでこれもstateで管理して、EDIT_CANCELのアクションが呼ばれるタイミングが操作をやめるときなので、そのタイミングでnullを代入してしまうのがいいんですかね...？

**Comment by konojunya** [comment]
#7 で修正したのでクローズします

**Comment by ryuone** [comment]
ありがとうございました！
